name: Move unassigned issues

on:
  issues:
    types:
      - unassigned

jobs:
  move-to-assigned:
    name: Move to backlog column
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus
        with:
          project: "adapt-authoring: The TODO Board"
          column: "Backlog"
          repo-token: ${{ secrets.PROJECTS_SECRET }}
